### ISSUE TITLE
1.12.62: how to define set_hwaddr for network interfaces?

### ISSUE THREAD

**Issue by jouvin** [quattor/aquilon#117]
With the new naming interface naming scheme introduced several years ago, it is cirtical to be able to define the property `set_hwaddr` for network interfaces. Is there a way to do it in Aquilon? Failure to do it means you endup with unpredictible names, not recognized as valid by most commands doing a validation of the interface names (like the `aq` command and several Quattor configuration modules), except by setting some specific kernel/Grub flags but it is not the recommended way.

**Comment by jrha** [comment]
We just have the following in `archetype/base`:
```pan
'/system/network/interfaces' = foreach(k; v; SELF) {
    SELF[k]['set_hwaddr'] = true;
    SELF;
};
```

**Comment by stdweird** [comment]
@jrha why not

```pan
"/system/network/set_hwaddr" ?= true;
```

**Comment by jrha** [comment]
:man_shrugging: Because we didn't know that it was a thing?

**Comment by stdweird** [comment]
@jrha despite the abundance of documentation? i'm shocked :duck:s

**Comment by jouvin** [comment]
I was also not aware of the possibility to set it globaly. Makes the workaround easy. But I still think that Aquilon should set this flag in the hostdata plenary template. I don't have a clear picture if using this flag can be harmful and has to be somewhat conditional.

**Comment by jrha** [comment]
IMHO these days it's more harmful to not set it. I don't think aquilon should support it, it seems more like a site policy decision possibly based on OS behaviour with different generations of hardware.

**Comment by ned21** [comment]
> I was also not aware of the possibility to set it globaly. Makes the workaround easy. But I still think that Aquilon should set this flag in the hostdata plenary template. I don't have a clear picture if using this flag can be harmful and has to be somewhat conditional.

But Aquilon hosts encompass more than just Linux. On other Ones and archetypes it's not allowed so you cannot put such a thing in the plenaries. In fact we have this:

```
aquilon/os/linux/base.pan: '/system/network/set_hwaddr' = true;
aquilon/os/solaris/final.pan: '/system/network/set_hwaddr' = false;
```

**Comment by jouvin** [comment]
Good point! We then need to make it clear in the documentation. I have an update of the base templates underway, I'll add it.

**Comment by jouvin** [comment]
@jrha not shure to understand your point. Do you want to say that this property default should be `true` rather than `false` in the schema? Or Do you want to say that it is more harmful to *set it* and we should not change anything, just inform the site that it has to decide (my current approach in https://github.com/quattor/quattor.github.com/pull/255)?

**Comment by jrha** [comment]
The point I was trying to make is that on modern Linux distributions it should IMHO always be set to `true`. 

However the ultimate decision rests with the site and is likely to be affected by many factors, including peculiarities of various hardware/software combinations and OS version. It is therefore business logic best managed by the Pan templates and not the broker.

**Comment by jouvin** [comment]
So we all agree at the end... Not sure it will work on Debian anyway... Closing this issue.
