### ISSUE TITLE
possible corruption of metadata in the aquilon externals yum repo

### ISSUE THREAD

**Issue by dzila** [quattor/aquilon#16]
Trying to install aquilon a new system I get the following message:

![aquilon](https://cloud.githubusercontent.com/assets/1721178/4163661/25e6d9ce-34ea-11e4-8737-a180c1d9d465.png)

**Comment by dzila** [comment]
bump

**Comment by dzila** [comment]
bump

**Comment by jrha** [comment]
repodata rebuilt and resigned today, the repository will be restructured soon though

**Comment by dzila** [comment]
Hi,

Problem is still there. I think repodata was not rebuilt at this particular folder as the files there are dated from March 2015: http://yum.quattor.org/externals/noarch/el6/repodata/

**Comment by dzila** [comment]
As discussed with James, the problem is in fact in the aquilon externals repo, not aquilon. I have fixed the title.

**Comment by jrha** [comment]
No longer applicable.
