### ISSUE TITLE
Starting procedure discrepency

### ISSUE THREAD

**Issue by samary** [quattor/aquilon#17]
There are 2 differents described way to start with aquilon : the README file of the github repo and the quattor website.

Which one is the correct to follow (I guess the website one) ?

I think we should just point the README to the official website documentation

**Comment by gombasg** [comment]
The two describe different things. The Quattor website talks about installing Aquilon from RPMs, while the README talks about what do you need to get it running from the source. So both are valid.

**Comment by jrha** [comment]
Maybe we should make that clearer and refer each to the other.

**Comment by jouvin** [comment]
Related to #31.

**Comment by urbonegi** [comment]
README inconsistencies fixed by removing all the contents and adding a link to the Quattor website.
