### ISSUE TITLE
Granular Permissions

### ISSUE THREAD

**Issue by jrha** [quattor/aquilon#18]
As discussed at the Grenoble workshop we would like a way to associate "users/principals" with hosts and other objects and use that information to restrict permission for `aq manage` and `aq make` for hosts.

It should also allow for super-users to `make` and `manage` any host.

This could be extended to personalities and features later.

**Comment by jouvin** [comment]
March 17 workshop: MS working on it, will come at some point in the future... Exact amount of work involved not yet clear, depends on the approach chosen.

**Comment by jrha** [comment]
Proposal is to pass a combination of GRN, User, Object and Ticket ID (if enabled) to a external access control mechanism.

**Comment by urbonegi** [comment]
Additional authorization controls added to multiple 'Change' commands (manage, make included). These trigger external utility which will not be open sourced now. However, the ChangeManagement class provides mechanism to calculate impacted environment and status of command impacted targets. Also validation method that allow/disallow action based on a response from the external utility. The Change Management class can be considered as an interface for writing your own Authentication library, as input and output for it is well defined. Authentication library can make Ownership (by eon_id), Role based access (by user, role, command) and Firm Change  Management (by dict_of_impacted_envs, ticket, enforce_justification) decisions.
https://github.com/quattor/aquilon/blob/upstream/lib/aquilon/worker/dbwrappers/change_management.py#L45
