### ISSUE TITLE
SHA1 checksum mismatch for aquilon-protocols-1.10

### ISSUE THREAD

**Issue by dzila** [quattor/aquilon#19]
Hi,

yum installation of aquilon using `yum -y install aquilon-postgresql` fails with:

`http://yum.quattor.org/aquilon/aquilon-protocols-1.10-1.noarch.rpm: [Errno -1] Package does not match intended download. Suggestion: run yum --enablerepo=aquilon clean metadata
Trying other mirror.
Error Downloading Packages:
  aquilon-protocols-1.10-1.noarch: failure: aquilon-protocols-1.10-1.noarch.rpm from aquilon: [Errno 256] No more mirrors to try.`

I suspect createrepo command needs to be run in the repo because in primary.xml the checksum is
`252c56f7707140b93c18c260b35b063e665b2f39`
but
`sha1sum aquilon-protocols-1.10-1.noarch.rpm`
`5aa885de61ab12819030d3841addf2fbd57fa6c2  aquilon-protocols-1.10-1.noarch.rpm`

**Comment by jrha** [comment]
Hmm, so why did the checksum change?

**Comment by dzila** [comment]
I do not know. I have installed the rpm manually meanwhile and then yum proceeded happily.

**Comment by dzila** [comment]
Ok this is actually a duplicate of an issue I opened in the last workshop https://github.com/quattor/aquilon/issues/16

**Comment by jrha** [comment]
ok, closing this one then
