### ISSUE TITLE
git dependency missing on aquilon

### ISSUE THREAD

**Issue by guillaume-philippon** [quattor/aquilon#21]
Following documentation, aquilon user need git-shell shell but git is not installed as dependency of aquilon.

Regards,

**Comment by jrha** [comment]
Of the RPM I assume?

**Comment by guillaume-philippon** [comment]
you assume well

**Comment by urbonegi** [comment]
I still do not see git here: https://github.com/quattor/aquilon/blob/upstream/setup.cfg
Assume this is not fixed? @guillaume-philippon @jrha
