### ISSUE TITLE
Problem with the yum repository?

### ISSUE THREAD

**Issue by JulienNauroy** [quattor/aquilon#22]
Hi,

I'm trying to install Aquilon using "yum -y install aquilon-postgresql" as stated here; http://www.quattor.org/documentation/2012/10/31/install-aquilon.html

Unfortunately, The download of http://yum.quattor.org/aquilon/aquilon-protocols-1.10-1.noarch.rpm fails with the following error : [Errno -1] Package does not match intended download

I've tried cleaning yum's cache but without success.

Is there a problem with the repository?

Julien

**Comment by jrha** [comment]
Yes, there is a problem with the way the package is generated, the version number is unfortunately hard-coded and a later version of the RPM overwrote an older one.

It's on my to-do list to fix.

**Comment by JulienNauroy** [comment]
I've just realized it's a duplicate of #16 
Closing my ticket.
