### ISSUE TITLE
Can't make aqd work properly

### ISSUE THREAD

**Issue by JulienNauroy** [quattor/aquilon#25]
Hi,
I can't find a way to make aqd work properly after running the tutorial and trying to debug here and there. Here are the symptoms:
1. When running aqd, here's what I get in the log:

```
2015-04-22 16:07:37+0200 [-] run_command: git describe (CWD: /usr/lib/python2.6)
2015-04-22 16:07:37+0200 [-] fatal: Not a git repository (or any of the parent directories): .git
2015-04-22 16:07:37+0200 [-] command `git describe` exited with return code 128
2015-04-22 16:07:37+0200 [-] command `git describe` stderr: fatal: Not a git repository (or any of the parent directories): .git

2015-04-22 16:07:37+0200 [-] Could not run git describe to get version: Command 'git describe' failed with return code '128' and stderr:
        fatal: Not a git repository (or any of the parent directories): .git

2015-04-22 16:07:37+0200 [-] Starting aqd version Unknown
```

I don't like the CWD value and 'not a git repository' error
1. When running aq, here's what I get:

```
-bash-4.1# aq.py show_archetype --all
Error: BadStatusLine('',): knc[23938]: gstd_error: gss_init_sec_context: Credentials cache file '/tmp/krb5cc_0' not found

```

Do you know where I've made a mistake in the configuration ?

**Comment by jrha** [comment]
The second error usually means you don't have a kerberos token for yourself (check with `klist`).
If you've got kerberos set up correctly a simple `kinit` should get you a token.

You can also try `aq.py status --noauth` to check the broker is responding.

**Comment by JulienNauroy** [comment]
`aq.py status --noauth` gives me the following error:

```
-bash-4.1# aq.py status --noauth
Internal Server Error: (ProgrammingError) ERREUR:  la relation « xtn » n'existe pas
LINE 1: INSERT INTO xtn (xtn_id, username, command, is_readonly, sta...
                    ^
 'INSERT INTO xtn (xtn_id, username, command, is_readonly, start_time) VALUES (%(xtn_id)s, %(username)s, %(command)s, %(is_readonly)s, %(start_time)s)' {'username': 'nobody', 'xtn_id': '0cc433d4-f7c1-11e4-8124-005056873f34', 'start_time': datetime.datetime(2015, 5, 11, 9, 35, 25, 65011, tzinfo=tzutc()), 'command': 'status', 'is_readonly': True}
```

You're right about the kerberos token. I'll see how to install a kerberos server.

Do you have an idea about the problem with `git describe`? I imagine it's a very simple problem, I've set up the `git_templates_url` in `aqd.conf` to multiple values with no result so far.

**Comment by jrha** [comment]
You shouldn't have to change `git_templates_url`.
Have you created and initialised the bare git repository in `/var/quattor/template-king/`?

**Comment by jrha** [comment]
Oh, actually the error you are seeing is the broker trying to find out what version it is, it does this by running `git describe` in the directory it is installed in. It seems to assume it was installed from source.

You could just do `git init` in the install directory, but that seems hackish.

@stdweird, what did you guys do to trick it?

**Comment by stdweird** [comment]
@jrha http://www.quattor.org/documentation/2012/10/31/install-aquilon.html is what @piojo did, and it has a `git init --bare`

**Comment by JulienNauroy** [comment]
Yes this is the tutorial I followed and I ran `git init --bare`.
Am I the only one running Aquilon from the RPMs?

**Comment by jrha** [comment]
Setting the broker version in the configuration file should fix this...

``` cfg
[broker]
version = 1.11.24_rc1
```

See `cache_version()` in https://github.com/quattor/aquilon/blob/6c8b90b47b19a41d974a41050e6de9e9ad850ae0/lib/python2.6/aquilon/worker/processes.py#L276.

It's assuming that the aquilon python files are in a git repository and trying to get the version from there, we should probably figure out a better way of doing this for the packaged version.

**Comment by JulienNauroy** [comment]
Thanks, it works now. So this had nothing to do with the templates Git repository.
Do you want me to create a separate issue for this specific problem so that it can be fixed in the RPM?

**Comment by jrha** [comment]
Yes please, I'll forget about it otherwise!

**Comment by JulienNauroy** [comment]
OK thanks for the help. I'll see what I can do with the Kerberos server. In the meantime, I'm closing this issue since it's become irrelevant.
