### ISSUE TITLE
aqd can't determine broker version from the RPMs

### ISSUE THREAD

**Issue by JulienNauroy** [quattor/aquilon#26]
One would have to add the following in aqd.conf:

``` cfg
[broker]
version = 1.11.24_rc1
```

It's related to the following method: https://github.com/quattor/aquilon/blob/6c8b90b47b19a41d974a41050e6de9e9ad850ae0/lib/python2.6/aquilon/worker/processes.py#L276

For more information, check issue #25

**Comment by jrha** [comment]
Three approaches come to mind:
1. Modify the default config file at build time to contain the current version number.
2. Write the version number to a file (`/etc/aqd-release`?) shipped by the RPM and get aquilon to check that file.
3. Extend the logic in `cache_version()` to check for installed RPMs.

**Comment by ned21** [comment]
@gombasg  notes that the code should set the version to "unknown" if it cannot determine a version, so there may be a simple bug in this code path that can be fixed.

**Comment by urbonegi** [comment]
seems to be done: https://github.com/quattor/aquilon/blob/1ecf0200b8bfdf219a76eb5b8a206e97cf5c3921/lib/aquilon/worker/processes.py#L231
