### ISSUE TITLE
Document use of Active Directory as a kerberos service

### ISSUE THREAD

**Issue by jrha** [quattor/aquilon#28]
As discussed at workshop, LAL use Active Directory so it would be useful if the experience and setup was written down for others to reference.

**Comment by jrha** [comment]
To clarify: I should contribute the recipe for how to extract the necessary keytabs and configuration from your local AD administrators.

**Comment by urbonegi** [comment]
hey @jrha is this done and can be closed? :)

**Comment by jrha** [comment]
No, but thanks for the reminder!

**Comment by ned21** [comment]
Also, how do you configure sssd to use Active Directory? ncm-authconfig has "freeipa" providers but no ad? Or is freeipa used for ad?

**Comment by stdweird** [comment]
@ned21 ad as sssd provider is just not supported yet. i guess it "only" requires schema extension to support it (so someone should read the `sssd-ad` man page and translate the option in a type)

**Comment by ned21** [comment]
@jrha will do this as part of upgrading the RAL broker to EL7
