### ISSUE TITLE
Document kerberos infrastructure options

### ISSUE THREAD

**Issue by jrha** [quattor/aquilon#29]
- Active Directory
- Locally administered KDC
- FreeIPA

**Comment by ned21** [comment]
Information on FreeIPA is available on [quattor.org](http://www.quattor.org/documentation/2015/09/30/freeipa-kerberos-quickstart.html)

**Comment by urbonegi** [comment]
@ned21 @jrha can this be closed? I found the docs around FreeIPA but not other...

**Comment by ned21** [comment]
Locally administered KDC is linked to from the Install Aquilon doc as http://tldp.org/HOWTO/Kerberos-Infrastructure-HOWTO/install.html.

Docs for using AD tracked in #28
