### ISSUE TITLE
README files still applicable?

### ISSUE THREAD

**Issue by kwaegema** [quattor/aquilon#31]
Is the README file of the repo still of value? 
There is also a README.dev in the etc folder, with instructions to install a dev broker, but the link is broken

**Comment by ned21** [comment]
Is this fixed by #36?

**Comment by ned21** [comment]
- [ ] etc/README.dev refers to internal MS stuff
- [x] need a document which describes how patches get accepted and the reason for each branch. e.g. never merge to upstream since that is reserved for the upstream authors.
- [x] Changes in #36 need to go to the correct place

**Comment by urbonegi** [comment]
README inconsistencies fixed by removing all the contents and adding a link to the Quattor website.

**Comment by ned21** [comment]
Doc on how to contribute is: http://www.quattor.org/aquilon/00-install.html#contributing
