### ISSUE TITLE
Path '/hardware/template_name' is not validate valid when binding HW features to models.

### ISSUE THREAD

**Issue by bmcann** [quattor/aquilon#39]
Hi Folks,

I am currently configuring all examples of a particular model in our DC to use 4 network links bonded via LACP. The approach I decided to take was to create a hardware feature and bind it to the model in question. So far, so good.

However, when I compile the profile, the compiler fails with an evaluation error:
> evaluation error [/var/quattor/cfg/plenary/ral-tier1/personality/ceph-gw/pre_feature.tpl:?]
> path `'/hardware/template_name'` does not have an associated value

When I add the key `/hardware/template_name` and a value for it to the machine template, the compiler fails with a validation error:
> validation error [/var/quattor/cfg/domains/nic-bonding/profiles/$fqdn.tpl]
> record definition contains unexpected field(s): template_name
> element path: '/hardware'

Is there a reason for using the path `/hardware/template_name` instead of `/hardware/model` as I would have expected the use of `/hardware/model`?

Best wishes,
Bruno

**Comment by gombasg** [comment]
The handling of hardware features was reworked in version 1.12.23, the broker no longer generates such template code.

**Comment by jrha** [comment]
Does this mean the schema needs updating?

**Comment by ned21** [comment]
@jrha - I can check but am not sure in which repo the public schema lives?

**Comment by jrha** [comment]
https://github.com/quattor/template-library-core/blob/master/quattor/types/aquilon.pan

**Comment by jrha** [comment]
It looks like `template_name` was never referred to by our copy of the schema (so all is good).
