### ISSUE TITLE
Unexpected template path when binding hardware feature to a model.

### ISSUE THREAD

**Issue by bmcann** [quattor/aquilon#40]
Hi Folks,

So I have a `feature` of type `hardware` in aquilon called `network/bonding-mode4`. I expect the associated template file to be: `~/$sandbox> $archetype/features/hardware/network/bonding-mode4/config.pan`.

However, when I bind the feature to a given model, the include statement created in the pre_feature template does not appear to have the correct path:
```
include {
        if ((value("/hardware/manufacturer") == "dell") &&
            (value("/hardware/template_name") == "r430-2015-cephgw")){
                return("features/hardware/network/bonding-mode4")
        } else{ return(undef); };
};
"/metadata/features"={
        if ((value("/hardware/manufacturer") == "dell") &&
            (value("/hardware/template_name") == "r430-2015-cephgw")){
                append("features/hardware/network/bonding-mode4/config");
        } else { SELF; };
};
```
I would expect line 4 to read `return("features/hardware/network/bonding-mode4/config")` not `return("features/hardware/network/bonding-mode4")`. Is this a bug?

Best wishes,
Bruno

**Comment by gombasg** [comment]
That was due to our template code using non-standard naming convention for hardware features. The current version of the broker uses `if_exists()` to support both the legacy and the standard naming.
