### ISSUE TITLE
Packages for EL7 should provide systemd unit files

### ISSUE THREAD

**Issue by jrha** [quattor/aquilon#43]
Rather than a System-V style init script.

In the meantime the init script is unusable with EL7 because it doesn't have the proper `chkconfig` support and is thus ignored by the `chkconfig` wrapper on EL7. Lines to add are something like:
```
# chkconfig: 2345 99 1
# description: Aquilon Broker
```

**Comment by ned21** [comment]
As noted in #23 the systemd unit should create /var/run/aquilon as owned by the aquilon user.

**Comment by urbonegi** [comment]
As this is merged can we close this issue:
https://github.com/quattor/aquilon/commit/a066bf7bcb1ec01e9d5a4b2728915c81bdffef10

**Comment by jrha** [comment]
Cool, thanks.

**Comment by stdweird** [comment]
@jrha @urbonegi euhm, why doesn't https://github.com/quattor/aquilon/commit/a066bf7bcb1ec01e9d5a4b2728915c81bdffef10 put th eunit in the proper place? `/usr/lib/systemd/system` is for unit files shipped by packages, anything in `/etc/systemd/system` (ie with `system` subdir) is for changes to unitfiles. with the current location, you can't change them (except by overwriting the whole unit).

also, if possible, don't ship both sysv init and unit files. people who use `service` commands to manage services might be in for a surprise 

and you need the extra `system` subdir, i don't think the current commit does work

**Comment by jrha** [comment]
The current commit doesn't put it anywhere, it just provides a unit file.

**Comment by stdweird** [comment]
@jrha ah, ok. the directory structure is a bit suggestive though

**Comment by jrha** [comment]
Sure, but in the context of the other files in the directory it makes sense.
