### ISSUE TITLE
aquilon-postgresql rpm dependency

### ISSUE THREAD

**Issue by samary** [quattor/aquilon#46]
The `aquilon-postgresql` rpm doesn't depend on `postgresql` as it should.

**Comment by stdweird** [comment]
is this really needed? i.e. can't it be a regular client of postgres, or does the postgresql has to run on the same host?

**Comment by jrha** [comment]
The idea of the `aquilon-postgresql` was to enable an easier install on one host, if you don't want that then just install `aquilon` and configure it yourself.

**Comment by stdweird** [comment]
what does `configure it yourself` mean? a set of pan templates is much better suited to install and configure what is needed, incl rpm deps.
bootstrapping a node with quattor is not that hard either

**Comment by jrha** [comment]
It means "work out how to set it up in a different way that makes you happy?" we haven't even got one setup figured out to the point that it works yet.

**Comment by urbonegi** [comment]
Aquilon broker can use postgres, oracle or sqlite as a databse backend. Moreover, database server could be on a different server.  Not using local postgres database should not prevent one from installing Aquilon broker. Btw, where is the aquilon-postgresql rpm defined? I only see this one: https://github.com/quattor/aquilon/blob/upstream/setup.cfg

**Comment by jrha** [comment]
Source of this package appears to have been lost, so won't fix.

**Comment by ned21** [comment]
Quattor templates are a better way to describe soft dependencies like this than a meta-rpm.
