### ISSUE TITLE
aqd.conf.defaults should not contain anything specific to MS

### ISSUE THREAD

**Issue by jouvin** [quattor/aquilon#49]
[`adq.conf.defaults`](https://github.com/quattor/aquilon/blob/upstream/etc/aqd.conf.defaults) provided in the source is opened by `aqd` in addition to the system `aqd.conf` to avoid having to write a full `aqd.conf`. But currently this file contains a lot of options with MS-specific values that prevent `aqd` to run successfully outside MS. This file should really be site-agnostic and MS-specific defaults should be moved somewhere else.

**Comment by ned21** [comment]
There's now a working process for accepting upstream submissions so we're happy for anyone to do this and send us the PR: http://www.quattor.org/aquilon/00-install.html#contributing
