### ISSUE TITLE
Aquilon tests require a version of git newer than provided in EL7

### ISSUE THREAD

**Issue by jrha** [quattor/aquilon#50]
I've started getting the unit tests to run on a stock(-ish) EL7 host, the first big failure is requiring `--no-patch` which appears to have been introduced in `1.8.4` (EL7 ships `1.8.3.1` 😞), however the release notes indicate that it was added as a synonym for existing functionality...

>  * "git show -s" was less discoverable than it should have been.  It
now has a natural synonym "git show --no-patch".

So switching this to `-s` should allow the stock git to work (I will test and report back).

```
FAIL: test_110_verifydeploylog (broker.test_deploy_domain.TestDeployDomain)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/tkk76468/aquilon/tests/broker/test_deploy_domain.py", line 58, in test_110_verifydeploylog
    out, _ = self.gitcommand(command, cwd=kingdir)
  File "/home/tkk76468/aquilon/tests/broker/brokertest.py", line 566, in gitcommand
    % (command, out, err))
AssertionError: Non-zero return code for ['show', '--no-patch', '--pretty=full', 'deployable'], STDOUT:
@@@
''
@@@
STDERR:
@@@
'fatal: unrecognized argument: --no-patch
'
@@@
```

**Comment by jrha** [comment]
Replacing `--no-patch` with `-s` does indeed allow the tests to pass.

**Comment by jrha** [comment]
Discussed at workshop: documentation should specify minimum git version.

**Comment by ned21** [comment]
We could patch this one instance but it's probably the tip of the iceberg since we are using 2.9. The [install doc](https://github.com/quattor/quattor.github.com/blob/master/_aquilon/00-install.md) should be updated to reflect this.

**Comment by stdweird** [comment]
please don't document dependency issues like this, but fix them in https://github.com/quattor/aquilon/blob/upstream/setup.cfg#L2. 
or at least make a pan template so we can install this with spma.
if we have basic templates that e.g. provide the package dependencies that aren't part of the rpm, or other things like config files or directories; it is very easy to bootstrap a host for aquilon usage and we can reuse the templates to manage the host with quattor.

**Comment by urbonegi** [comment]
@stdweird  I agree - this is not something that should be documented. It should be rather added to the dependencies file. I can add the explicit requirement of git >= 1.8.4 to setup.cfg just would be good if someone could test this installer outside MS with all he recent patches that were merged in.
https://github.com/quattor/aquilon/pull/70
