### ISSUE TITLE
build_db.py creates a prod domain without creating the Git branch

### ISSUE THREAD

**Issue by jouvin** [quattor/aquilon#53]
`build_db.py` initializes the Aquilon database with a `prod` domain whose content matches what is expected for running unit tests. But if unit tests are not run, the corresponding Git branch is not created in the `template_king` repository and `aq add_domain --domain prod` cannot create it as the domain already exists in the database. The only workaround is to create the branch manually in the Git repository.

2 actions are probably needed:
* [ ] `build_db.py` should not create a `prod` domain by default. Such a creation should be done only if a specific option is given.
* [ ] `aq add_domain` should have an option to fix the missing Git branch if the domain already exists in the database

**Comment by urbonegi** [comment]
There is a script that checks and fixes inconsistencies between DB and templates in the Git repo:
https://github.com/quattor/aquilon/blob/upstream/sbin/aqd_consistency_check.py
To ensure the build_db.py script only creates the DB but not adds data to it, you should not pass option '--populate' https://github.com/quattor/aquilon/blob/d7254a55af8a55533d21ca427eec00bcad241f94/tests/aqdb/build_db.py#L75
Or edit the contents of a data in this file (this is where the data is being populated from): 
https://github.com/quattor/aquilon/blob/d7254a55af8a55533d21ca427eec00bcad241f94/tests/aqdb/data/unittest.dump

**Comment by ned21** [comment]
This came up at the Annecy workshop. It looks like the [documentation](https://github.com/quattor/quattor.github.com/blob/master/_aquilon/00-install.md) is now correct, in that the "Git Daemon Configuration" section tells the user to create a prod branch manually.
