### ISSUE TITLE
Documentation: move all the Aquilon documentation in a single repository

### ISSUE THREAD

**Issue by jouvin** [quattor/aquilon#57]
Currently, Aquilon documentation is spread between this repository (`README.md` describing the installation) and the [web site](http://www.quattor.org/documentation/2013/10/25/aquilon-site.html) (describing Aquilon DB configuration). I think that we should have on the documentation on one side, either this repo or the web site repo. I see pro and cons for both solutions:
- Pro (this repo):
  - Having it colocated with the code increases the chance to have it up-to-date
- Cons (this repo):
  - This information is mainly maintained by the community, not Aquilon developers
  - The web site allows better rendering thanks to Jekyll (and its CSS)
  - There is a complex workflow to merge this repo contents with the repo used by the main developers (outside GH)

So I would probably support moving everything to the web site.

In addition, after everything has been moved into one repo, I suggest that we process it  as part of the Quattor release documentation that we put on ReadTheDocs.

**Comment by jouvin** [comment]
Note that the answer to this question may impact #56 and https://github.com/quattor/quattor.github.com/pull/211.

**Comment by ned21** [comment]
+1 to this - I think it makes a lot of sense.
