### ISSUE TITLE
Deleting prod domain fails

### ISSUE THREAD

**Issue by jouvin** [quattor/aquilon#60]
I tried to delete the `prod` domain after archiving it: This results in a strange Git error:
```
[aquilon@vm-79119 /]$ aq del domain --domain prod --justification emergency --reason "remove domain created for unit tests"                                  
Bad Request: 
Cloning into 'trash'...
fatal: Remote branch trash not found in upstream origin
fatal: The remote end hung up unexpectedly
```
Attempt to create the `trash` branch (does not really make sense) triggers another error referring to missing identity configuration in Git which is also strange (as it is done and not reported for other commands):
```
[aquilon@vm-79119 /]$ aq del domain --domain prod --justification emergency --reason "remove domain created for unit tests"
Bad Request: 
error: duplicate parent 705efacbfcc749cf681f618c9f9cbf3230b2ba0d ignored

*** Please tell me who you are.

Run

  git config --global user.email "you@example.com"
  git config --global user.name "Your Name"

to set your account's default identity.
Omit --global to set the identity only in this repository.

fatal: empty ident name (for <aquilon@vm-79119.lal.in2p3.fr>) not allowed
```

**Comment by urbonegi** [comment]
@jouvin 
Creating a trash branch should be a part of intial quattor aquilon setup and should be added to the docs here: http://www.quattor.org/aquilon/00-install.html (in the Git Daemon Configuration section).
Not sure how you added the 'trash' branch, it would be forbidden to create the trash branch using add domain command as this name is 'reserved':
https://github.com/quattor/aquilon/blob/upstream/lib/aquilon/worker/dbwrappers/branch.py#L144
Anyway, why not setting up git config --global user.email "you@example.com" & git config --global user.name "Your Name"? Especially, if it is in the set up documentation for quattor aquilon anyway:
http://www.quattor.org/aquilon/00-install.html (at section Git Daemon Configuration).
Let me know if after setup of user and email there are still issues with deleting domain.
Btw, one can change the 'trashs' domain name specifying it in the settings (so potentially it can be changed to any existing branch):
[broker]
trash_branch = unittest_trash

**Comment by jouvin** [comment]
@urbonegi thanks for your answer. I have not payed enough attention to the fact that the failure may have been caused by the missing Git configuration. I'll try again and let you know if this is enough to remove the error. If you don't mind, let this is issue open but I am not sure I'll be able to do a test anytime soon. May be later in July.

**Comment by urbonegi** [comment]
@jouvin Have you looked at this one? You should create trash branch manually using git commands. Setting git username and email also should be done as part of Application setup. Maybe we could close it?

**Comment by ned21** [comment]
This is the file that needs amending: https://github.com/quattor/quattor.github.com/blob/master/_aquilon/00-install.md

**Comment by jrha** [comment]
Discussed at RAL workshop: missing step from documentation, probably should be scripted, but at least documented.

**Comment by urbonegi** [comment]
https://github.com/quattor/quattor.github.com/pull/225
