### ISSUE TITLE
RPM updates for py27

### ISSUE THREAD

**Issue by ned21** [quattor/aquilon#72]
_Originally opened by @ajf8 as https://github.com/quattor/release/issues/263_

The current latest el6 RPMs do not work because Aquilon now requires python 2.7. As discussed at the workshop we should probably just kill the el6 repositories and focus on el7, and update the documentation (in a separate issue).

The knc and python-twisted-runner RPMs were added during the workshop to get the current version in the el7 repository to install. Here are two additional RPMs (and SRPMs) which are needed to get the latest version of Aquilon to build and run on el7:

aquilon-protocols-1.29 - built from 1.29 tag but needed the setup.py from master for bdist_rpm to work. we will look at fixing the setup.py in upstream.
python-sqlalchemy-1.0.14 - built from a Fedora SRPM. 

http://eth0.org.uk/~alan/quattor_rpms/

**Comment by ned21** [comment]
@jrha  to add to externals repo

**Comment by jrha** [comment]
Done.
