### ISSUE TITLE
1.12.58: archetype/final should be optional

### ISSUE THREAD

**Issue by jouvin** [quattor/aquilon#83]
Currently the broker created profiles where the last line is `include { "archetype/final" };`. I can imagine that the this template is not necessarily needed and rather than creating it empty, I'd suggest that this line is replaced by:
```
include if_exists('archetype/final');
```
Note that an optional template is still part of the dependency information, so if it is added later, it will cause the profiles to be recompliled.

**Comment by jrha** [comment]
It's pretty much essential for all normal use-cases (it's the only safe way to force profile content), but I see your point.

**Comment by jouvin** [comment]
After more experience with Aquilon and a discussion with @urbonegi , I agree that these templates have to exist in a real configuration and that it is better to expose that they are missing.
