### ISSUE TITLE
Problem with post dependencies and ncm-ncd --nodeps

### ISSUE THREAD

**Issue by nowack73** [quattor/aquilon#9]
I am wondering why ncm-ncd (13.3) behaves unexpected when I use --nodeps.
I would like to run only one single component (e.g. accounts). 
Accounts has a post dependency requiring filecopy.

If I run "ncm-ncd --configure accounts  --verbose --nodeps --autodeps=0 --debug 9" I get this:

> # ncm-ncd --configure accounts --verbose --nodeps --autodeps=0 --debug 9
> 
> [INFO] NCM-NCD version 13.3.0 started by root at: Fri Mar 22 14:21:11 2013
> [VERB] accessing CCM cache manager..
> [VERB] getting locked CCM configuration..
> [VERB] checking for ncm-ncd locks...
> [INFO] Ignoring broken pre/post dependencies (--nodeps flag set)
> [DEBUG] pre dependencies for component accounts spma
> [DEBUG] post dependencies for component accounts filecopy
> [INFO] executing configure on components....
> 
> [ERROR] post-requisite for component  "accounts" does not exist: filecopy
> [ERROR] cannot sort components according to dependencies
> # 
> 
> [INFO] Errors while configuring 
> [ERROR] 1 errors, 0 warnings executing configure

"--nodeps" ignores the pre dependency (spma) as expected, but the post dependency causes an error.

If I look into NCD::ComponentProxyList, I find this in _sortComponents():

> ```
>   foreach (@post) {
> ```
> 
>   unless (defined $comps{$_}) {
>     unless ($this_app->option('nodeps')) {
>       $self->error('pre-requisite for component "'.$name.'"  does not exist: '.$_);
>       return undef;
>     }
>     $self->error('post-requisite for component  "'.$name.'" does not exist: '.$_);
>     return undef;
>   }
>   $after->{$name}->{$_}=1;
>       }

This looks strange. "--nodeps" does not have any effect on post dependencies. 
But the help says: "--nodeps: ignore broken (pre/post) dependencies in configure"

This problem is not new, also older versions of ncm-ncd show this behaviour.

**Comment by jrha** [comment]
I don't think this is an Aquilon issue.

**Comment by nowack73** [comment]
Sorry, I am not familiar with GitHub and was not aware of the multitude of ticket systems here.
