### ISSUE TITLE
aq.py ignores system-wide conf file if run from the sources

### ISSUE THREAD

**Issue by jouvin** [quattor/aquilon#98]
In 1.12.60, `aq.py` intentionally ignores  the system-wide conf file if a `Makefile` file is found in the parent directory of the script (typically means run from the source tree). This default behaviour is annoying as the typical Aquilon deployment documented is a `git clone`. Would it be acceptable to have an option on the command line (and possibly in the system-wide conf file) to enable this behaviour rather than having it as the default?

**Comment by stdweird** [comment]
the "typical" deployment is a git clone? really? doesn't aquilon do releases?

**Comment by jrha** [comment]
@stdweird yes, but releases do not imply packages or anything else other than a defined point in a commit tree

**Comment by stdweird** [comment]
@jrha i meant releases on pypi and such. anyway, is this also an issue with the rpms?

**Comment by jrha** [comment]
:man_shrugging:

**Comment by ned21** [comment]
I suspect there are two cases where this could be important:
1. Running the unit tests. 
2. Running development instances, it is important that the developer does not accidentally run commands against the real production instance.

It may be better to do as @stdweird suggests and ensure the client is run from a properly packaged instance instead of a source tree that may be ahead of the running broker.

**Comment by jouvin** [comment]
I think my point/issue is a little bit distinct from the packaging. Yes it would be great to have a PyPi package for Aquilon but honestly, having doing it as documented with a Git clone, I don't see any major issue and it has also its advantages in this phase where things evolve quicly: easy to test changes, rollback, run PRs not yet committed...

My point is about the default behaviour regarding the config file location. Currently, there is a [line](https://github.com/quattor/aquilon/blob/c9495232e1460d832b81e71c4bdd92f8b9936599/lib/aquilon/config.py#L58) that makes the heuristic to decide (silently) the path of the config file completely different whether you run from the source tree or not. And I find this behaviour at least discussable and possibly a source of pain when troubleshooting problems. I understand the intent but I am not convinced that the default behaviour should be for running unit tests as this is a context generally involving a script where it is easy to pass a command line option to say that you are in this context and wants some things to be done differently. As for a development instance, it is something that is normally installed and configured on a more permanent basis and you can ensure that you have the proper config files for it.

That said, I'm attached to backward compatibility and there was a choice made a while ago. I'd like to minimize the changes to this behaviour but still fixing the current behaviour that I find not really appropriate : you can install only from the Git repo but to have the client working as expected (with a system-wide config file outside the source tree), you have to delete the Makefile that is part of the repo, meaning that if you want to take advantage of the fact that you have a Git repo, you have a great chance to make a mistake and commit this removal. Thus the fixed that I proposed in #99 which consists to keep the current behaviour for locating the config file for `aqd` daemon and everything else except the client (`aq.py`) as only the client is really impacted by the current behaviour. In case of the client it is still possible to use an explicit broker with the appropriate global option or the env variables and the risk of doing something wrong should be limited by the authorization involved in passing the commands. If it is seen as desirable, it would be easy to add a global option like `--development` that would implement the current behaviour (ignore system-wide config file).

As explained in #99, the real source of the problem for the client is that the source path is returned unconditionnally if the source tree (the Makefile) is detected, whether it contains an `aq` (client) config file or not. Another approach (that I'm happy to implement if it is thought better!) is to return the source tree path only if contains a config file (which is not the case by default). As in the current PR, it could be done only for the client (with the use a new argument to `lookup_file_path()`.

**Comment by ned21** [comment]
Thanks for the detailed reply. I am not opposed to this change in anyway, was just trying to explain why the current behaviour might have seemed desirable (although changing  something "silently" is almost always wrong). I will leave this to the determination of active developers such as @urbonegi who have to be careful to avoid running commands against production!

**Comment by jouvin** [comment]
Thanks! As I said, the PR is the beginning of an attempt to make the life in production easier... I'm really ready to improve it to make easy to ensure that you are not running against the wrong broker because you used the wrong config file, in particular by adding a global option like `--ignore-system-config`. I'm looking forward @urbonegi feedback.

**Comment by urbonegi** [comment]
If we introduce these changes that means that every developer who have their dev environment will have to always export aqhost/aqservice to make sure they hit their dev server not production. It is too bit overhead and will definitely cause us hitting prod endpoints by accident quite often. Having default behavior after git clone to use localhost as dev server is best solution. Please note that MS have shared FS - if we start looking at the conf files elsewhere than source code - we endup with prod endpoint defaults. 
The easiest way for you to move forward is just not use same bin/aq.py in the source code directory (use the fact that aq server and client are completely separated). Just have additional - 'prod' deployment with bin/aq which is installed as rpm or some custom Makefile and does not contain Makefile itself :) then if you use bin/aq to call Aquilon server it will not default to source code dir but rather will look for aq.conf in root directories first (/etc/aquilon and /usr/share/aquilon/etc). Moreover, it make sense to use aq.conf which is in code source dir if one runs bin/aq.py from source code dir...

**Comment by jouvin** [comment]
@urbonegi may be my issue description was not clear enough but the problem that I see is that there is no `aq.conf` in shte source tree by default. So returning the source tree as the location for the config file unconditionally is not completely consistent. You could imaging to create one as part of the Makefile for example. I don't think that it necessarily requires a developper to define env variables. But clearly it will change a little bit the behaviour...

I'll try to update #99 with the other approach I proposed to better illustrate how it could work. Installating Aquilon client with something else than a Git clone would work, just it doesn't exist today! If there is not any change acceptable for you, we can certainly live with a local workaround. Note that the current behaviour is not a problem when the client runs on the same machine as the broker but when you want to install it on another machine (because the default `localhost` doesn't work).

**Comment by urbonegi** [comment]
You have 3 options to fix this:
1. Have a aq.conf in the source code and just adding a line in .gitignore to ignore it. The aq.conf is internal and custom per organization so it cannot be pushed to github code repo. 
2. 'Deploy' the source code to new dir (remove the Makefile), then you can use the aq.conf in /etc/aquilon and not one in source code dir. You can just simply always use that to call any aqd server :) client code changes not so often so you can have it separately sitting somewhere else. You can even create and alias for 'aq' to call the correct path of the client script.
3. You could just pass the --aqconf _path_to_client_config which fixes your problem :) this seems more appropriate than introducing new option --devmode which creates risk for us :)

**Comment by jouvin** [comment]
Probably options 1 and 2 are acceptable but they are still workarounds (option 1 will be acceptable if we can commit the modified `.gitignore`). option 3 is not more acceptable than it is for you to add an option everytime you run `aq.py` in development mode... I'm still trying to find a solution acceptable for you (I understood that it means a solution changing nothing for you) and fixing the default behaviour for other sites. 
Thinking a little bit more about it, that is was may not desesperate :smile: Currently, when no `Makefile` is detected, the config file search path is (from https://github.com/quattor/aquilon/blob/c9495232e1460d832b81e71c4bdd92f8b9936599/lib/aquilon/config.py#L61):
```
/etc/aquilon
/usr/share/etc/aquilon
$SRC_DIR/../../../aqd-vcs/prod/etc
$SRC_DIR/etc
```
If I understood properly, MS is not using `/etc/aquilon` and `/usr/share/etc/aquilon` but rather `$SRC_DIR/../../../aqd-vcs/prod/etc` that nobody else uses. And that it is this directory that must be ignored for a change not have any impact on you. Is is right? If yes, I'd propose to implement a modified `lookup_file_path()` where, if the `Makefile` is detected, the directory `$SRC_DIR/../../../aqd-vcs/prod/etc` is ignored and `$SRC_DIR/etc` is inserted first in the list. This way, the change would have no impact on MS and for other sites, if you want to have a specific setting for you development instance you could have an `aq.conf` in the source tree that would take precedence over the system-wide one.

Would this be acceptable ?!

**Comment by ned21** [comment]
@jouvin Acceptable to us does not mean "change nothing", it means "fail safe by not talking to production if a developer has checked out the source tree".  That's a good thing for everyone, not just us, and also using the aq client from HEAD is incompatible with talking to an older broker version.

I think deploying code via git clone is actually a pretty good deployment mechanism.  But that's not to say that "git clone" is the only step. @urbonegi's options (1) and (2) are straightforward to implement in quattor. For (1), you are already delivering an aq.conf to /etc/aquilon (I assume via quattor) so this just requires to change the destination to the location of your aq client directory. (I'm not even sure you need a .gitignore file: but if it's necessary then filecopy can add it.)

For (2), @urbonegi tells me you just need two files (aq.py and input.xml) so you filecopy those from your clone to /usr/local/bin (or whatever is convenient for your $PATH). Then your update procedure is something that does:

```
cd /usr/src/aquilon
git checkout $new-tag
ncm-ncd --configure filecopy
```

@urbonegi is taking a look at your most recent proposal. We do also use /etc/aquilon in newer environments but she will take a look to see if there a combination that works.

**Comment by jouvin** [comment]
Thanks! I'm waiting for @urbonegi's feedback on my last proposal (not yet implemented!). The client deployment is not difficult, you are right, but it is a little bit more than the files you mentioned. At least `lib/aquilon/config.py` is missing. At some point it may be good to have the exhaustive list somewhere...

**Comment by urbonegi** [comment]
@jouvin  Sorry to take so long to respond - I was occupied by some internal work. So although your solution sounds good @jouvin it will also not work for us, as we use the directories mentioned. We ship /etc/aquilon/aq.conf with a help of quattor templates to aquilon hosts so that they can communicate with the aqd. I think at the end state you can also achieve that as well. Reading what @ned21  and you suggested the best approach is this:
1. Have your aqconf managed in separate internal project.
2. As part as aqd deployment do git clone of the main source code and the aq config project (anywhere you like)
3. Add symlink in your aqd/etc/aq.conf which points to your aq conf project aq.conf file
4. Submit PR for us to add etc/aq.conf to .gitignore
I think that would be best and require leas changes for everyone habits..
Alternately:
-Use aq.conf what will be deployed in /etc/aquilon/aq.conf - but just delete Makefile so that 'devmode' test will return False. This requires no changes at all :)
